BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE messages CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE user_obj';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE user_table';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE message_obj';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE message_table';
EXCEPTION WHEN OTHERS THEN NULL;
END;

-- Создание таблицы пользователей
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password_hash VARCHAR2(200) NOT NULL
);

-- Создание таблицы сообщений
CREATE TABLE messages (
    message_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    content VARCHAR2(1000) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

Select * from messages
/*2a*/


CREATE OR REPLACE TYPE message_obj AS OBJECT (
    message_id NUMBER,
    user_id NUMBER,
    content VARCHAR2(1000)
);

CREATE OR REPLACE TYPE message_table AS TABLE OF message_obj;



CREATE OR REPLACE TYPE user_obj AS OBJECT (
    user_id NUMBER,
    username VARCHAR2(50),
    email VARCHAR2(100),
    messages message_table
);

CREATE OR REPLACE TYPE user_table AS TABLE OF user_obj;
SET SERVEROUTPUT ON;

/*2b*/

INSERT INTO users (username, email, password_hash) VALUES ('user1', 'user1@example.com', 'hashed_password1');
INSERT INTO users (username, email, password_hash) VALUES ('user2', 'user2@example.com', 'hashed_password2');
INSERT INTO users (username, email, password_hash) VALUES ('user3', 'user3@example.com', 'hashed_password3');
INSERT INTO users (username, email, password_hash) VALUES ('user4', 'user4@example.com', 'hashed_password4');
INSERT INTO users (username, email, password_hash) VALUES ('user5', 'user5@example.com', 'hashed_password5');

INSERT INTO messages (user_id, content) VALUES (1, 'Hello from user1!');
INSERT INTO messages (user_id, content) VALUES (1, 'Another message from user1.');
INSERT INTO messages (user_id, content) VALUES (2, 'Hi, this is user2.');
INSERT INTO messages (user_id, content) VALUES (3, 'User3 here, nice to meet you!');
INSERT INTO messages (user_id, content) VALUES (4, 'User4 sending a message!');
INSERT INTO messages (user_id, content) VALUES (3, '123!');
INSERT INTO messages (user_id, content) VALUES (4, '123!');
COMMIT;

DECLARE
    k1 user_table;
    v_found BOOLEAN;
BEGIN
    -- Выборка данных 
    SELECT user_obj(user_id, username, email, 
                    CAST(MULTISET(
                        SELECT message_obj(message_id, user_id, content) 
                        FROM messages WHERE messages.user_id = users.user_id) AS message_table))
    BULK COLLECT INTO k1 FROM users;
    
    -- Выводим всех пользователей и их сообщения
    FOR i IN 1..k1.COUNT LOOP
        DBMS_OUTPUT.PUT_LINE('Пользователь: ' || k1(i).username);
        FOR j IN 1..k1(i).messages.COUNT LOOP
            DBMS_OUTPUT.PUT_LINE('Сообщение: ' || k1(i).messages(j).content);
        END LOOP;
    END LOOP;
    
    -- Ищем пересечения сообщений между пользователями
    FOR i IN 1..k1.COUNT LOOP
        FOR j IN 1..k1(i).messages.COUNT LOOP
            FOR k IN i+1..k1.COUNT LOOP
                FOR m IN 1..k1(k).messages.COUNT LOOP
                    IF k1(i).messages(j).content = k1(k).messages(m).content THEN
                        DBMS_OUTPUT.PUT_LINE('Пользователь ' || k1(i).username || 
                                             ' пересекается с пользователем ' || k1(k).username ||
                                             ' по сообщению: ' || k1(i).messages(j).content);
                    END IF;
                END LOOP;
            END LOOP;
        END LOOP;
    END LOOP;
    
    -- Ищем пользователя с user_id = 1 
    v_found := FALSE;
    FOR i IN 1..k1.COUNT LOOP
        IF k1(i).user_id = 1 THEN   
            v_found := TRUE;
            EXIT;
        END IF;
    END LOOP;
    IF v_found THEN
        DBMS_OUTPUT.PUT_LINE('Пользователь с ID=1 найден');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Пользователь с ID=1 не найден');
    END IF;
    
    -- Находим пользователей без сообщений
    FOR i IN 1..k1.COUNT LOOP
        IF k1(i).messages IS EMPTY THEN
            DBMS_OUTPUT.PUT_LINE('Пользователь ' || k1(i).username || ' не имеет сообщений');
        END IF;
    END LOOP;
    
    -- Обмен сообщениями между двумя пользователями
    IF k1.COUNT > 1 THEN
        DECLARE
            temp_messages message_table;
        BEGIN
            temp_messages := k1(1).messages;
            k1(1).messages := k1(2).messages;
            k1(2).messages := temp_messages;
            DBMS_OUTPUT.PUT_LINE('Сообщения между пользователями 1 и 2 обменяны');
            
            DBMS_OUTPUT.PUT_LINE('Сообщения пользователя 1:');
            FOR j IN 1..k1(1).messages.COUNT LOOP
                DBMS_OUTPUT.PUT_LINE('Сообщение: ' || k1(1).messages(j).content);
            END LOOP;
            
            DBMS_OUTPUT.PUT_LINE('Сообщения пользователя 2:');
            FOR j IN 1..k1(2).messages.COUNT LOOP
                DBMS_OUTPUT.PUT_LINE('Сообщение: ' || k1(2).messages(j).content);
            END LOOP;
        END;
    END IF;
END;

/*3*/
SELECT 
    u.user_id,
    u.username,
    u.email,
    m.message_id,
    m.content
FROM users u
LEFT JOIN (
    SELECT 
        m.message_id,
        m.user_id,
        m.content
    FROM messages m 
) m ON m.user_id = u.user_id;

/*4*/

DECLARE
    -- Объявляем тип записи для сообщения
    TYPE message_rec IS RECORD (
        message_id NUMBER,
        user_id NUMBER,
        content VARCHAR2(1000)
    );

    -- Объявляем коллекцию для сообщений
    TYPE message_tab IS TABLE OF message_rec;
    messages_to_update message_tab;

BEGIN
    -- Извлекаем сообщения из таблицы messages
    SELECT message_id, user_id, content 
    BULK COLLECT INTO messages_to_update
    FROM messages;

    -- Обновляем содержимое каждого сообщения
    FORALL i IN 1 .. messages_to_update.COUNT
        UPDATE messages
        SET content = messages_to_update(i).content || ' - update'
        WHERE message_id = messages_to_update(i).message_id;

    COMMIT;
END;

-- Проверка BULK операции
SELECT message_id, user_id, content FROM messages;


/*------------------------------------------------10------------------------------------------------*/
