//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airplanes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Airplanes()
        {
            this.CrewMembers = new HashSet<CrewMembers>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
        public string Model { get; set; }
        public int PassengerSeats { get; set; }
        public int YearOfManufacture { get; set; }
        public decimal CargoCapacity { get; set; }
        public System.DateTime LastMaintenanceDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrewMembers> CrewMembers { get; set; }
    }
}
