/*1*/
Select GROUPS.PROFESSION, PROGRESS.SUBJECT,avg(PROGRESS.NOTE)[Средняя оценка]
From PROGRESS inner join Student
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
inner join GROUPS
on GROUPS.IDGROUP = STUDENT.IDGROUP
inner join FACULTY
on FACULTY.FACULTY = GROUPS.FACULTY
where GROUPS.FACULTY like '%ТОВ%'
group by ROLLUP (PROGRESS.SUBJECT,GROUPS.PROFESSION,FACULTY.FACULTY);


/*2*/
Select GROUPS.PROFESSION, PROGRESS.SUBJECT,avg(PROGRESS.NOTE)[Средняя оценка]
From PROGRESS inner join Student
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
inner join GROUPS
on GROUPS.IDGROUP = STUDENT.IDGROUP
inner join FACULTY
on FACULTY.FACULTY = GROUPS.FACULTY
where GROUPS.FACULTY like '%ТОВ%'
group by CUBE (PROGRESS.SUBJECT,GROUPS.PROFESSION,FACULTY.FACULTY);


/*3*/
Select GROUPS.PROFESSION, PROGRESS.SUBJECT,avg(PROGRESS.NOTE)[Средняя оценка]
From PROGRESS inner join Student
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
inner join GROUPS
on GROUPS.IDGROUP = STUDENT.IDGROUP
where GROUPS.FACULTY like '%ТОВ%'
group by PROGRESS.SUBJECT,GROUPS.PROFESSION
Union
Select GROUPS.PROFESSION, PROGRESS.SUBJECT,avg(PROGRESS.NOTE)[Средняя оценка]
From PROGRESS inner join Student
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
inner join GROUPS
on GROUPS.IDGROUP = STUDENT.IDGROUP
where GROUPS.FACULTY like '%ХТиТ%'
group by PROGRESS.SUBJECT,GROUPS.PROFESSION

/*Union All*/
Select GROUPS.PROFESSION, PROGRESS.SUBJECT,avg(PROGRESS.NOTE)[Средняя оценка]
From PROGRESS inner join Student
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
inner join GROUPS
on GROUPS.IDGROUP = STUDENT.IDGROUP
where GROUPS.FACULTY like '%ТОВ%'
group by PROGRESS.SUBJECT,GROUPS.PROFESSION
Union all
Select GROUPS.PROFESSION, PROGRESS.SUBJECT,avg(PROGRESS.NOTE)[Средняя оценка]
From PROGRESS inner join Student
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
inner join GROUPS
on GROUPS.IDGROUP = STUDENT.IDGROUP
where GROUPS.FACULTY like '%ХТиТ%'
group by PROGRESS.SUBJECT,GROUPS.PROFESSION

/*4*/
Select GROUPS.PROFESSION, PROGRESS.SUBJECT,avg(PROGRESS.NOTE)[Средняя оценка]
From PROGRESS inner join Student
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
inner join GROUPS
on GROUPS.IDGROUP = STUDENT.IDGROUP
where GROUPS.FACULTY like '%ТОВ%'
group by PROGRESS.SUBJECT,GROUPS.PROFESSION
INTERSECT
Select GROUPS.PROFESSION, PROGRESS.SUBJECT,avg(PROGRESS.NOTE)[Средняя оценка]
From PROGRESS inner join Student
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
inner join GROUPS
on GROUPS.IDGROUP = STUDENT.IDGROUP
where GROUPS.FACULTY like '%ХТиТ%'
group by PROGRESS.SUBJECT,GROUPS.PROFESSION

/*5*/
Select GROUPS.PROFESSION, PROGRESS.SUBJECT,avg(PROGRESS.NOTE)[Средняя оценка]
From PROGRESS inner join Student
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
inner join GROUPS
on GROUPS.IDGROUP = STUDENT.IDGROUP
where GROUPS.FACULTY like '%ТОВ%'
group by PROGRESS.SUBJECT,GROUPS.PROFESSION
EXCEPT
Select GROUPS.PROFESSION, PROGRESS.SUBJECT,avg(PROGRESS.NOTE)[Средняя оценка]
From PROGRESS inner join Student
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
inner join GROUPS
on GROUPS.IDGROUP = STUDENT.IDGROUP
where GROUPS.FACULTY like '%ХТиТ%'
group by PROGRESS.SUBJECT,GROUPS.PROFESSION

/*7*/
select FACULTY.FACULTY, GROUPS.IDGROUP, count(STUDENT.IDSTUDENT)[кол-во студентов]
from FACULTY inner join GROUPS
on FACULTY.FACULTY = GROUPS.FACULTY
inner join STUDENT
on GROUPS.IDGROUP = STUDENT.IDGROUP
group by rollup (FACULTY.FACULTY, GROUPS.IDGROUP)


select AUDITORIUM.AUDITORIUM_CAPACITY,AUDITORIUM.AUDITORIUM_TYPE, count(AUDITORIUM.AUDITORIUM)[кол-во айдиторий]
from AUDITORIUM  
group by cube (AUDITORIUM.AUDITORIUM_CAPACITY, AUDITORIUM.AUDITORIUM_TYPE);