/*1*/
Select PULPIT.PULPIT_NAME
From PULPIT,FACULTY
Where FACULTY.FACULTY = PULPIT.FACULTY 
and PULPIT.FACULTY in (Select FACULTY From PROFESSION
Where (PROFESSION_NAME LIKE '%технологии%' or PROFESSION_NAME LIKE '%технология%'))
/*2*/
Select PULPIT.PULPIT_NAME
From PULPIT inner join Faculty 
ON FACULTY.FACULTY = PULPIT.FACULTY
Where PULPIT.FACULTY in (Select FACULTY From PROFESSION
Where (PROFESSION_NAME LIKE '%технологии%' or PROFESSION_NAME LIKE '%технология%'))
/*3*/
Select DISTINCT PULPIT.PULPIT_NAME
From PULPIT 
inner join FACULTY ON FACULTY.FACULTY = PULPIT.FACULTY 
inner join PROFESSION ON PROFESSION.FACULTY = PULPIT.FACULTY 
Where (PROFESSION_NAME LIKE '%технологии%' or PROFESSION_NAME LIKE '%технология%')
/*4*/
Select AUDITORIUM.AUDITORIUM, AUDITORIUM.AUDITORIUM_CAPACITY, AUDITORIUM.AUDITORIUM_TYPE
From AUDITORIUM 
where AUDITORIUM.AUDITORIUM_CAPACITY in (
Select top(1) a.AUDITORIUM_CAPACITY 
From AUDITORIUM a
where a.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE
order by a.AUDITORIUM_CAPACITY desc)
order by AUDITORIUM.AUDITORIUM_CAPACITY desc
/*5*/
Select FACULTY.FACULTY_NAME From FACULTY
Where not exists (
Select *from PULPIT
where PULPIT.FACULTY = FACULTY.FACULTY)
/*6*/
Select top 1
(select avg(Note) from PROGRESS where PROGRESS.SUBJECT like 'ОАиП')[Ср. ОАиП],
(select avg(Note) from PROGRESS where PROGRESS.SUBJECT like 'БД')[Ср. БД],
(select avg(Note) from PROGRESS where PROGRESS.SUBJECT like 'СУБД')[Ср. СУБД]
From PROGRESS
/*7*/
Select  PROGRESS.IDSTUDENT, PROGRESS.NOTE 
from PROGRESS
where Progress.NOTE <=all (select PROGRESS.NOTE from PROGRESS where PROGRESS.SUBJECT like 'ОаиП')
/*8*/
Select  PROGRESS.IDSTUDENT, PROGRESS.NOTE 
from PROGRESS
where Progress.IDSTUDENT >any (select PROGRESS.IDSTUDENT from PROGRESS where PROGRESS.NOTE = 9)
/*9*/
SELECT distinct STUDENT.NAME,  S1.NAME, S1.BDAY
       FROM STUDENT INNER JOIN STUDENT S1
       ON STUDENT.BDAY = S1.BDAY AND STUDENT.IDSTUDENT <> S1.IDSTUDENT;