// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMeezLbs0d1DiOOkNXV2o_jdBaHwxpni4',
    appId: '1:663361758623:web:ec899100e39446484109aa',
    messagingSenderId: '663361758623',
    projectId: 'lab11-ff22d',
    authDomain: 'lab11-ff22d.firebaseapp.com',
    storageBucket: 'lab11-ff22d.firebasestorage.app',
    measurementId: 'G-BQSQQ5EZ3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxrKS6ZsujGUdnmIVLqyKQRlqsR4N15OM',
    appId: '1:663361758623:android:d10f8bd3eb33e8f04109aa',
    messagingSenderId: '663361758623',
    projectId: 'lab11-ff22d',
    storageBucket: 'lab11-ff22d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_wfaJ2OROoH1fi9Bw2gPjDiTWUm5GruY',
    appId: '1:663361758623:ios:b8c78ff558a2544d4109aa',
    messagingSenderId: '663361758623',
    projectId: 'lab11-ff22d',
    storageBucket: 'lab11-ff22d.firebasestorage.app',
    iosBundleId: 'com.example.lab11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_wfaJ2OROoH1fi9Bw2gPjDiTWUm5GruY',
    appId: '1:663361758623:ios:b8c78ff558a2544d4109aa',
    messagingSenderId: '663361758623',
    projectId: 'lab11-ff22d',
    storageBucket: 'lab11-ff22d.firebasestorage.app',
    iosBundleId: 'com.example.lab11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMeezLbs0d1DiOOkNXV2o_jdBaHwxpni4',
    appId: '1:663361758623:web:20707dd5cff951d14109aa',
    messagingSenderId: '663361758623',
    projectId: 'lab11-ff22d',
    authDomain: 'lab11-ff22d.firebaseapp.com',
    storageBucket: 'lab11-ff22d.firebasestorage.app',
    measurementId: 'G-1G9KN67CG5',
  );
}
